name = "StagedFunctions"
uuid = "6517edbf-059c-472a-a5de-1137718a67f1"
authors = ["Nathan Daly <nhdaly@gmail.com>", "Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.4"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "Test"]
